### ISSUE TITLE
Adding tags plugin seems to have broken search

### ISSUE THREAD

**Issue by jprui** [ixti/redmine_tags#106] opened 2015-04-22 18:57 UTC
After adding the tags plugin, an error was received when trying to do a search. There seems to be an error in the SQL where the tags is not being joined and maybe conflicting with one of the other plugins.

The plugins loaded are:

clipboard_image_paste
open_flash_chart
project_alias
redmine_banner
redmine_charts2
redmine_embedded
redmine_favourite_projects
redmine_plugin_views_revisions
redmine_release_notes
redmine_silencer
redmine_wiki_extensions
redmine_wiki_notes

Error message:
```
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'tags.name' in 'where clause': SELECT COUNT(DISTINCT `wiki_pages`.`id`) FROM `wiki_pages` LEFT OUTER JOIN `wikis` ON `wikis`.`id` = `wiki_pages`.`wiki_id` LEFT OUTER JOIN `projects` ON `projects`.`id` = `wikis`.`project_id` LEFT OUTER JOIN `wiki_contents` ON `wiki_contents`.`page_id` = `wiki_pages`.`id` LEFT OUTER JOIN `wiki_extensions_tag_relations` ON `wiki_extensions_tag_relations`.`wiki_page_id` = `wiki_pages`.`id` LEFT OUTER JOIN `wiki_extensions_tags` ON `wiki_extensions_tags`.`id` = `wiki_extensions_tag_relations`.`tag_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='wiki')) AND (((LOWER(title) LIKE '%linux%') OR (LOWER(wiki_contents.text) LIKE '%linux%') OR (LOWER(tags.name) LIKE '%linux%')))):
```

If We added a "LEFT OUTER JOIN `tags` ON `tags`.`id` = `wiki_extensions_tags`.`id` " clause to the SQL, it fixed the syntactical error.
but given I know close to 0 about ruby, etc... I didn't want to mess...

So we have disabled the tags plugin for now.

**Comment by pka23** [comment] 2015-06-18 07:23
**Same search error from redmine production.log:**
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'tags.name' in 'where clause': SELECT DISTINCT `issues`.`created_on`, `issues`.`id` FROM `issues` INNER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` WHERE (((projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) AND (projects.id IN (1,2,20,21,22,23,24,25,35,36,37,38,67,72) OR projects.id IN (2,4,5,6,7,8,9,10,11,12,13,14,17,19,20,21,22,23,24,25,27,28,29,31,32,36,37,39,40,41,42,43,45,46,47,49,50,51,56,57,58,63,65,66,68,69,70,71,75,76,77,78,79,80) OR (projects.id IN (3,28,29,32,34,40,41,42,43,49,50,52,56,57,58,70,78,79) AND ((issues.is_private = 0 OR issues.author_id = 4 OR issues.assigned_to_id IN (4,12,13,23)))) OR (projects.id IN (4,5,6,7,8,9,10,11,12,13,14,17,19,30,31,39,45,49,50,56,57,58,75,76,77,80) AND ((issues.is_private = 0 OR issues.author_id = 4 OR issues.assigned_to_id IN (4,12,13,23))))))) AND (issues.project_id IN (29)) AND (((subject LIKE '%ipad%') OR (issues.description LIKE '%ipad%') OR (tags.name LIKE '%ipad%')))  ORDER BY `issues`.`created_on` DESC, `issues`.`id` DESC):
  lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:179:in `fetch_ranks_and_ids'
  lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:91:in `search_result_ranks_and_ids'
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:65:in `index'

**Wiki page error:**
Started GET "/projects/PROJECT_NAME/wiki" for 172.16.3.8 at 2015-06-18 10:21:11 +0300
Processing by WikiController#show as HTML
  Parameters: {"project_id"=>"PROJECT_ID"}
  Current user: prokin (id=4)
  Rendered attachments/_form.html.erb (7.2ms)
  Rendered wiki/edit.html.erb within layouts/base (14.4ms)
  Rendered plugins/redmine_tags/app/views/wiki/_tags_sidebar.html.erb (1.8ms)
Completed 500 Internal Server Error in 130ms

ActionView::Template::Error (undefined method `to_sql' for {:conditions=>["projects.id=?", 32]}:Hash):
    1: <% unless sidebar_tags.empty? -%>
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', :plugin => 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', :plugin => 'redmine_tags' %>
    4:   <h3><%= l(:tags) %></h3>
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/helpers/application_helper.rb:1229:in `view_layouts_base_sidebar_hook_response'
  app/helpers/application_helper.rb:1225:in `sidebar_content?'
  app/views/layouts/base.html.erb:50:in `_app_views_layouts_base_html_erb__2841294231280288387_70237501901340'
  app/controllers/wiki_controller.rb:73:in `show'

**Comment by PowerKiKi** [comment] 2015-12-03 05:56
Assuming this was with Redmine 3, closing as duplicate of #104

**Closed by PowerKiKi** 2015-12-03 05:56 UTC
Labels: Bug
