### ISSUE TITLE
Undefined local variable or method 'sidebar_tags'

### ISSUE THREAD

**Issue by asrmarco13** [ixti/redmine_tags#130] opened 2016-02-16 09:58 UTC
Hello,
I have the following error:
![internal_error_500](https://cloud.githubusercontent.com/assets/17269293/13072774/661f033e-d49b-11e5-9626-6c57bb8bc933.png)

I click '**Import**' in tab **Issue**:
![import_link](https://cloud.githubusercontent.com/assets/17269293/13072851/c44e9d66-d49b-11e5-8e0d-8add1daeabe8.png)

Can you help me? 

Redmine info:
![redmine_info](https://cloud.githubusercontent.com/assets/17269293/13072896/00c23be0-d49c-11e5-8f2f-b3a87810e252.png)

Production log:
`Started GET "/redmine/issues/imports/new" for 192.168.51.119 at 2016-02-16 10:46:38 +0100
Processing by ImportsController#new as HTML
  Current user: morfei (id=4)
  Rendered plugins/redmine_tags/app/views/issues/_tags_sidebar.html.erb (36.7ms)
  Rendered issues/_sidebar.html.erb (38.6ms)
  Rendered imports/new.html.erb within layouts/base (41.7ms)
Completed 500 Internal Server Error in 152ms (ActiveRecord: 94.3ms)

ActionView::Template::Error (undefined local variable or method `sidebar_tags' for #<#<Class:0x007f1c0eec57a8>:0x007f1c0eecd7a0>):
    1: <% if !sidebar_tags.empty? && !@issue %>
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
    4:   <h3><%= l :tags %></h3>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:22:in `_app_views_issues__sidebar_html_erb___1122257528374917323_69879242045880'
  app/views/imports/new.html.erb:14:in `block in _app_views_imports_new_html_erb__1457699941058388125_69879243135380'
  app/views/imports/new.html.erb:13:in `_app_views_imports_new_html_erb__1457699941058388125_69879243135380'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

**Comment by sdwolf** [comment] 2016-02-16 12:12
I've commited a fix for this on master.

**Comment by lacek** [comment] 2016-02-16 13:14
This is a duplicate of #125

**Comment by asrmarco13** [comment] 2016-02-16 13:23
It works! Thank you very much sdwolf!

**Closed** 2016-02-16 13:26 UTC

**Comment by sdwolf** [comment] 2016-02-16 13:53
@asrmarco13  :beers:
